export const CardAttributeType = {
   NEAR:                    1,      // 近
   FAR:                     2,      // 遠
   RUSH:                    3,      // 連
   RANGE:                   4,      // 周
   HEAL:                    5,      // 癒
   GUARD:                   6,      // 防
   BUFF:                    7,      // 強
   DEBUFF:                  8,      // 弱
   WARP:                    9,      // 移
   TRAP:                    10,     // 罠
   COUNTER:                 11,     // 返
   DISPEL:                  12,     // 除
   POISON:                  13,     // 毒
   SILENCE:                 14,     // 黙
   STUN:                    15,     // 止
   FLASH:                   16,     // 閃
   DISRUPT:                 17,     // 害
   UNIT:                    18,     // 人
   PUSH:                    19,     // 押
   PULL:                    20,     // 引
   BREAK:                   21,     // 破
   PIERCE:                  22,     // 貫
   STEAL:                   23,     // 奪
   ABSORB:                  24,     // 吸
   REGEN:                   25,     // 続
   BLAST:                   26,     // 爆
   KEY:                     27,     // 鍵
   ALL:                     28,     // 全
   RETREAT:                 29,     // 帰
   WAVE:                    30,     // 波
   CURE:                    31,     // 異
   ENEMY:                   32,     // 敵
   WALL:                    33,     // 壁
   COPY:                    34,     // 偽
   SHOT:                    35,     // 撃
   HASTE:                   36,     // 縮
   SMOKE:                   37,     // 煙
   RING:                    38,     // 帯
   WING:                    39,     // 翼
   LAUNCH:                  40,     // 昇
   FRONT:                   41,     // 前
   EXPAND:                  42,     // 拡
   BOOST:                   43,     // 加
   KNOCKDOWN:               44,     // 倒
   DEPLOY:                  45,     // 置
   AWAY:                    46,     // 離
   APPLY:                   47,     // 与
   SYNC:                    48,     // 共
   CIRCLE:                  49,     // 円
   SOUL:                    50,     // 魂
} as const;

export type CardAttributeType = typeof CardAttributeType[keyof typeof CardAttributeType];